export interface QuizQuestion {
  id: string;
  question: string;
  options: string[];
  correctAnswer: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export const ENGLISH_QUIZ_QUESTIONS: QuizQuestion[] = [
  // Easy (17)
  { id: 'e1', question: "Was bedeutet 'apple' auf Deutsch?", options: ["Apfel", "Birne", "Banane"], correctAnswer: "Apfel", difficulty: "easy" },
  { id: 'e2', question: "Welches Wort ist ein Wochentag?", options: ["Monday", "Month", "Morning"], correctAnswer: "Monday", difficulty: "easy" },
  { id: 'e3', question: "He ___ a book.", options: ["reads", "read", "reading"], correctAnswer: "reads", difficulty: "easy" },
  { id: 'e4', question: "She ___ playing tennis.", options: ["is", "am", "are"], correctAnswer: "is", difficulty: "easy" },
  { id: 'e5', question: "Was heißt 'Hund' auf Englisch?", options: ["cat", "dog", "bird"], correctAnswer: "dog", difficulty: "easy" },
  { id: 'e6', question: "They ___ at home yesterday.", options: ["were", "was", "are"], correctAnswer: "were", difficulty: "easy" },
  { id: 'e7', question: "I ___ to school every day.", options: ["go", "goes", "going"], correctAnswer: "go", difficulty: "easy" },
  { id: 'e8', question: "Was ist die Mehrzahl von 'child'?", options: ["children", "childs", "childrens"], correctAnswer: "children", difficulty: "easy" },
  { id: 'e9', question: "Welche Farbe hat eine Zitrone auf Englisch?", options: ["yellow", "red", "blue"], correctAnswer: "yellow", difficulty: "easy" },
  { id: 'e10', question: "How ___ are you?", options: ["old", "age", "years"], correctAnswer: "old", difficulty: "easy" },
  { id: 'e11', question: "I have ___ apple.", options: ["an", "a", "the"], correctAnswer: "an", difficulty: "easy" },
  { id: 'e12', question: "Das Gegenteil von 'big' ist:", options: ["small", "tall", "long"], correctAnswer: "small", difficulty: "easy" },
  { id: 'e13', question: "We ___ breakfast at 7 am.", options: ["have", "has", "having"], correctAnswer: "have", difficulty: "easy" },
  { id: 'e14', question: "Wie schreibt man 'Fenster'?", options: ["window", "windo", "wondow"], correctAnswer: "window", difficulty: "easy" },
  { id: 'e15', question: "Look at ___ bird!", options: ["that", "this", "these"], correctAnswer: "that", difficulty: "easy" },
  { id: 'e16', question: "My mother's sister is my ___.", options: ["aunt", "uncle", "cousin"], correctAnswer: "aunt", difficulty: "easy" },
  { id: 'e17', question: "Can you ___ me, please?", options: ["help", "helps", "helping"], correctAnswer: "help", difficulty: "easy" },
  { id: 'e18', question: "Was bedeutet 'Katze' auf Englisch?", options: ["cat", "mouse", "dog"], correctAnswer: "cat", difficulty: "easy" },
  { id: 'e19', question: "Welches Wort ist eine Zahl?", options: ["three", "tree", "there"], correctAnswer: "three", difficulty: "easy" },
  { id: 'e20', question: "I ___ a student.", options: ["am", "is", "are"], correctAnswer: "am", difficulty: "easy" },
  { id: 'e21', question: "Was heißt 'Wasser' auf Englisch?", options: ["water", "fire", "earth"], correctAnswer: "water", difficulty: "easy" },
  { id: 'e22', question: "The sun ___ shining.", options: ["is", "am", "are"], correctAnswer: "is", difficulty: "easy" },
  { id: 'e23', question: "He ___ pizza.", options: ["likes", "like", "liking"], correctAnswer: "likes", difficulty: "easy" },
  { id: 'e24', question: "Was ist das Gegenteil von 'good'?", options: ["bad", "nice", "well"], correctAnswer: "bad", difficulty: "easy" },
  { id: 'e25', question: "My name ___ John.", options: ["is", "are", "am"], correctAnswer: "is", difficulty: "easy" },
  { id: 'e26', question: "How ___ you?", options: ["are", "is", "am"], correctAnswer: "are", difficulty: "easy" },
  { id: 'e27', question: "I have two ___.", options: ["hands", "handes", "hand"], correctAnswer: "hands", difficulty: "easy" },
  { id: 'e28', question: "Welche Farbe hat der Himmel?", options: ["blue", "green", "red"], correctAnswer: "blue", difficulty: "easy" },
  { id: 'e29', question: "Guten Morgen heißt:", options: ["Good morning", "Good night", "Good evening"], correctAnswer: "Good morning", difficulty: "easy" },
  { id: 'e30', question: "She ___ playing the piano.", options: ["is", "does", "has"], correctAnswer: "is", difficulty: "easy" },
  { id: 'e31', question: "Was heißt 'Milch'?", options: ["milk", "juice", "tea"], correctAnswer: "milk", difficulty: "easy" },
  { id: 'e32', question: "I ___ not know.", options: ["do", "does", "am"], correctAnswer: "do", difficulty: "easy" },
  { id: 'e33', question: "Das ist mein Buch:", options: ["This is my book", "That is me book", "This are my book"], correctAnswer: "This is my book", difficulty: "easy" },
  { id: 'e34', question: "He is my ___.", options: ["brother", "sister", "mother"], correctAnswer: "brother", difficulty: "easy" },

  // Medium (17)
  { id: 'm1', question: "I ___ a movie when the phone rang.", options: ["was watching", "watched", "watching"], correctAnswer: "was watching", difficulty: "medium" },
  { id: 'm2', question: "If it rains, we ___ at home.", options: ["will stay", "stay", "stayed"], correctAnswer: "will stay", difficulty: "medium" },
  { id: 'm3', question: "She is the ___ girl in the class.", options: ["tallest", "taller", "most tall"], correctAnswer: "tallest", difficulty: "medium" },
  { id: 'm4', question: "He drives very ___.", options: ["fast", "fastly", "faster"], correctAnswer: "fast", difficulty: "medium" },
  { id: 'm5', question: "I have ___ finished my homework.", options: ["already", "yet", "still"], correctAnswer: "already", difficulty: "medium" },
  { id: 'm6', question: "Was ist das Partizip Perfekt (Past Participle) von 'go'?", options: ["gone", "went", "going"], correctAnswer: "gone", difficulty: "medium" },
  { id: 'm7', question: "They ___ English for three years.", options: ["have been learning", "are learning", "learn"], correctAnswer: "have been learning", difficulty: "medium" },
  { id: 'm8', question: "You ___ smoke in a hospital.", options: ["mustn't", "don't have to", "needn't"], correctAnswer: "mustn't", difficulty: "medium" },
  { id: 'm9', question: "Das Gegenteil von 'expensive' ist:", options: ["cheap", "poor", "low"], correctAnswer: "cheap", difficulty: "medium" },
  { id: 'm10', question: "Who did you ___ at the party?", options: ["see", "saw", "seen"], correctAnswer: "see", difficulty: "medium" },
  { id: 'm11', question: "The book is ___ the table.", options: ["on", "in", "at"], correctAnswer: "on", difficulty: "medium" },
  { id: 'm12', question: "I am interested ___ reading books.", options: ["in", "about", "for"], correctAnswer: "in", difficulty: "medium" },
  { id: 'm13', question: "Are there ___ apples left?", options: ["any", "some", "no"], correctAnswer: "any", difficulty: "medium" },
  { id: 'm14', question: "We don't have ___ time.", options: ["much", "many", "a lot"], correctAnswer: "much", difficulty: "medium" },
  { id: 'm15', question: "Let's go to the park, ___ we?", options: ["shall", "will", "do"], correctAnswer: "shall", difficulty: "medium" },
  { id: 'm16', question: "Was bedeutet 'to apologize'?", options: ["sich entschuldigen", "sich aufregen", "sich bedanken"], correctAnswer: "sich entschuldigen", difficulty: "medium" },
  { id: 'm17', question: "He told me that he ___ tired.", options: ["was", "is", "were"], correctAnswer: "was", difficulty: "medium" },
  { id: 'm18', question: "If I ___ time, I will help you.", options: ["have", "had", "will have"], correctAnswer: "have", difficulty: "medium" },
  { id: 'm19', question: "They ___ playing football when it started raining.", options: ["were", "are", "have been"], correctAnswer: "were", difficulty: "medium" },
  { id: 'm20', question: "She ___ to London next week.", options: ["is traveling", "travels", "traveled"], correctAnswer: "is traveling", difficulty: "medium" },
  { id: 'm21', question: "I have lived here ___ 2010.", options: ["since", "for", "ago"], correctAnswer: "since", difficulty: "medium" },
  { id: 'm22', question: "This is the ___ book I have ever read.", options: ["best", "goodest", "better"], correctAnswer: "best", difficulty: "medium" },
  { id: 'm23', question: "He asked me what ___.", options: ["I wanted", "did I want", "do I want"], correctAnswer: "I wanted", difficulty: "medium" },
  { id: 'm24', question: "I couldn't sleep ___ the noise.", options: ["because of", "because", "due"], correctAnswer: "because of", difficulty: "medium" },
  { id: 'm25', question: "If you heat ice, it ___.", options: ["melts", "will melt", "melted"], correctAnswer: "melts", difficulty: "medium" },
  { id: 'm26', question: "He plays the guitar very ___.", options: ["well", "good", "nice"], correctAnswer: "well", difficulty: "medium" },
  { id: 'm27', question: "She had her hair ___ yesterday.", options: ["cut", "cutting", "cuts"], correctAnswer: "cut", difficulty: "medium" },
  { id: 'm28', question: "Was bedeutet 'to postpone'?", options: ["verschieben", "absagen", "bestätigen"], correctAnswer: "verschieben", difficulty: "medium" },
  { id: 'm29', question: "Would you mind ___ the window?", options: ["closing", "to close", "close"], correctAnswer: "closing", difficulty: "medium" },
  { id: 'm30', question: "I'm looking forward to ___ you.", options: ["seeing", "see", "seen"], correctAnswer: "seeing", difficulty: "medium" },
  { id: 'm31', question: "You ___ better see a doctor.", options: ["had", "would", "should"], correctAnswer: "had", difficulty: "medium" },
  { id: 'm32', question: "There were ___ people at the concert.", options: ["a lot of", "much", "many of"], correctAnswer: "a lot of", difficulty: "medium" },
  { id: 'm33', question: "Neither John ___ Mary came.", options: ["nor", "or", "and"], correctAnswer: "nor", difficulty: "medium" },

  // Hard (16)
  { id: 'h1', question: "If I ___ you, I would study harder.", options: ["were", "was", "am"], correctAnswer: "were", difficulty: "hard" },
  { id: 'h2', question: "The window ___ broken by the boy.", options: ["was", "had", "did"], correctAnswer: "was", difficulty: "hard" },
  { id: 'h3', question: "She asked me where ___.", options: ["I lived", "did I live", "do I live"], correctAnswer: "I lived", difficulty: "hard" },
  { id: 'h4', question: "Not only ___ late, but he also forgot his books.", options: ["was he", "he was", "did he"], correctAnswer: "was he", difficulty: "hard" },
  { id: 'h5', question: "I wish I ___ more money.", options: ["had", "have", "will have"], correctAnswer: "had", difficulty: "hard" },
  { id: 'h6', question: "She is used ___ early.", options: ["to waking up", "to wake up", "waking up"], correctAnswer: "to waking up", difficulty: "hard" },
  { id: 'h7', question: "By this time tomorrow, I ___ the project.", options: ["will have finished", "will finish", "have finished"], correctAnswer: "will have finished", difficulty: "hard" },
  { id: 'h8', question: "I remember ___ him at the conference last year.", options: ["meeting", "to meet", "meet"], correctAnswer: "meeting", difficulty: "hard" },
  { id: 'h9', question: "Was bedeutet 'obsolete'?", options: ["veraltet", "absolute", "unhöflich"], correctAnswer: "veraltet", difficulty: "hard" },
  { id: 'h10', question: "He denied ___ the window.", options: ["breaking", "to break", "break"], correctAnswer: "breaking", difficulty: "hard" },
  { id: 'h11', question: "It's high time we ___.", options: ["left", "leave", "are leaving"], correctAnswer: "left", difficulty: "hard" },
  { id: 'h12', question: "Scarcely ___ asleep when the phone rang.", options: ["had I fallen", "I had fallen", "I fell"], correctAnswer: "had I fallen", difficulty: "hard" },
  { id: 'h13', question: "Was ist ein Synonym für 'ubiquitous'?", options: ["omnipresent", "rare", "expensive"], correctAnswer: "omnipresent", difficulty: "hard" },
  { id: 'h14', question: "I'd rather you ___ smoke here.", options: ["didn't", "don't", "won't"], correctAnswer: "didn't", difficulty: "hard" },
  { id: 'h15', question: "Despite ___, she went to work.", options: ["being ill", "she was ill", "illness"], correctAnswer: "being ill", difficulty: "hard" },
  { id: 'h16', question: "The ___ you study, the better your grades will be.", options: ["more", "most", "much"], correctAnswer: "more", difficulty: "hard" },
  { id: 'h17', question: "By the time we arrive, the film ___.", options: ["will have started", "will start", "started"], correctAnswer: "will have started", difficulty: "hard" },
  { id: 'h18', question: "Had I known, I ___ you.", options: ["would have helped", "would help", "will help"], correctAnswer: "would have helped", difficulty: "hard" },
  { id: 'h19', question: "He insisted ___ paying for the meal.", options: ["on", "for", "to"], correctAnswer: "on", difficulty: "hard" },
  { id: 'h20', question: "She is not accustomed ___ working so late.", options: ["to", "with", "for"], correctAnswer: "to", difficulty: "hard" },
  { id: 'h21', question: "Was bedeutet 'to procrastinate'?", options: ["Dinge aufschieben", "aktiv sein", "lügen"], correctAnswer: "Dinge aufschieben", difficulty: "hard" },
  { id: 'h22', question: "It is crucial that he ___ present.", options: ["be", "is", "will be"], correctAnswer: "be", difficulty: "hard" },
  { id: 'h23', question: "Barely ___ entered the room when everyone cheered.", options: ["had she", "she had", "she has"], correctAnswer: "had she", difficulty: "hard" },
  { id: 'h24', question: "This is a ___ debated topic.", options: ["hotly", "hot", "heatedly"], correctAnswer: "hotly", difficulty: "hard" },
  { id: 'h25', question: "No sooner had I sat down ___ the phone rang.", options: ["than", "when", "then"], correctAnswer: "than", difficulty: "hard" },
  { id: 'h26', question: "Was ist ein Synonym für 'eloquent'?", options: ["articulate", "silent", "rude"], correctAnswer: "articulate", difficulty: "hard" },
  { id: 'h27', question: "He ___ have been there; I saw him myself.", options: ["must", "can't", "should"], correctAnswer: "must", difficulty: "hard" },
  { id: 'h28', question: "Never before ___ such a beautiful sunset.", options: ["have I seen", "I have seen", "I saw"], correctAnswer: "have I seen", difficulty: "hard" },
  { id: 'h29', question: "If it hadn't been for your help, I ___.", options: ["would have failed", "failed", "will fail"], correctAnswer: "would have failed", difficulty: "hard" },
  { id: 'h30', question: "He was on the verge of ___.", options: ["crying", "cry", "cried"], correctAnswer: "crying", difficulty: "hard" },
  { id: 'h31', question: "It goes ___ saying that you're welcome here.", options: ["without", "under", "beyond"], correctAnswer: "without", difficulty: "hard" },
  { id: 'h32', question: "Was bedeutet 'ephemeral'?", options: ["kurzlebig", "ewig", "schlammig"], correctAnswer: "kurzlebig", difficulty: "hard" },
  { id: 'h33', question: "She was taken ___ by the surprise party.", options: ["aback", "over", "away"], correctAnswer: "aback", difficulty: "hard" },
];

export const MATH_QUIZ_QUESTIONS: QuizQuestion[] = [
  // Easy (17)
  { id: 'math_e1', question: "Was ist 5 + 7?", options: ["10", "11", "12"], correctAnswer: "12", difficulty: "easy" },
  { id: 'math_e2', question: "Was ist 15 - 8?", options: ["6", "7", "8"], correctAnswer: "7", difficulty: "easy" },
  { id: 'math_e3', question: "Was ist 3 * 4?", options: ["12", "14", "9"], correctAnswer: "12", difficulty: "easy" },
  { id: 'math_e4', question: "Was ist 20 / 4?", options: ["4", "5", "6"], correctAnswer: "5", difficulty: "easy" },
  { id: 'math_e5', question: "Was ist 100 - 45?", options: ["65", "55", "45"], correctAnswer: "55", difficulty: "easy" },
  { id: 'math_e6', question: "Was ist 8 + 9?", options: ["16", "17", "18"], correctAnswer: "17", difficulty: "easy" },
  { id: 'math_e7', question: "Was ist 6 * 6?", options: ["30", "36", "42"], correctAnswer: "36", difficulty: "easy" },
  { id: 'math_e8', question: "Was ist 50 / 5?", options: ["10", "5", "15"], correctAnswer: "10", difficulty: "easy" },
  { id: 'math_e9', question: "Was ist 25 + 35?", options: ["50", "60", "70"], correctAnswer: "60", difficulty: "easy" },
  { id: 'math_e10', question: "Was ist 9 * 3?", options: ["24", "27", "30"], correctAnswer: "27", difficulty: "easy" },
  { id: 'math_e11', question: "Was ist 40 - 18?", options: ["22", "32", "28"], correctAnswer: "22", difficulty: "easy" },
  { id: 'math_e12', question: "Was ist 7 * 5?", options: ["30", "35", "40"], correctAnswer: "35", difficulty: "easy" },
  { id: 'math_e13', question: "Was ist 18 / 3?", options: ["5", "6", "7"], correctAnswer: "6", difficulty: "easy" },
  { id: 'math_e14', question: "Was ist 12 + 19?", options: ["29", "31", "41"], correctAnswer: "31", difficulty: "easy" },
  { id: 'math_e15', question: "Was ist 8 * 4?", options: ["32", "24", "28"], correctAnswer: "32", difficulty: "easy" },
  { id: 'math_e16', question: "Was ist 100 / 10?", options: ["1", "10", "100"], correctAnswer: "10", difficulty: "easy" },
  { id: 'math_e17', question: "Was ist 45 + 55?", options: ["90", "100", "110"], correctAnswer: "100", difficulty: "easy" },
  { id: 'math_e18', question: "Was ist 10 + 10?", options: ["20", "10", "30"], correctAnswer: "20", difficulty: "easy" },
  { id: 'math_e19', question: "Was ist 14 - 7?", options: ["7", "6", "8"], correctAnswer: "7", difficulty: "easy" },
  { id: 'math_e20', question: "Was ist 2 * 8?", options: ["16", "14", "18"], correctAnswer: "16", difficulty: "easy" },
  { id: 'math_e21', question: "Was ist 30 / 6?", options: ["5", "4", "6"], correctAnswer: "5", difficulty: "easy" },
  { id: 'math_e22', question: "Was ist 11 + 11?", options: ["22", "11", "33"], correctAnswer: "22", difficulty: "easy" },
  { id: 'math_e23', question: "Was ist 50 - 25?", options: ["25", "20", "30"], correctAnswer: "25", difficulty: "easy" },
  { id: 'math_e24', question: "Was ist 3 * 3?", options: ["9", "6", "12"], correctAnswer: "9", difficulty: "easy" },
  { id: 'math_e25', question: "Was ist 16 / 4?", options: ["4", "2", "8"], correctAnswer: "4", difficulty: "easy" },
  { id: 'math_e26', question: "Was ist 5 * 5?", options: ["25", "20", "30"], correctAnswer: "25", difficulty: "easy" },
  { id: 'math_e27', question: "Was ist 100 / 2?", options: ["50", "40", "60"], correctAnswer: "50", difficulty: "easy" },
  { id: 'math_e28', question: "Was ist 12 - 5?", options: ["7", "6", "8"], correctAnswer: "7", difficulty: "easy" },
  { id: 'math_e29', question: "Was ist 4 * 7?", options: ["28", "24", "32"], correctAnswer: "28", difficulty: "easy" },
  { id: 'math_e30', question: "Was ist 9 + 8?", options: ["17", "16", "15"], correctAnswer: "17", difficulty: "easy" },
  { id: 'math_e31', question: "Was ist 20 / 5?", options: ["4", "5", "6"], correctAnswer: "4", difficulty: "easy" },
  { id: 'math_e32', question: "Was ist 33 + 33?", options: ["66", "60", "70"], correctAnswer: "66", difficulty: "easy" },
  { id: 'math_e33', question: "Was ist 6 * 4?", options: ["24", "20", "28"], correctAnswer: "24", difficulty: "easy" },
  { id: 'math_e34', question: "Was ist 81 / 9?", options: ["9", "8", "7"], correctAnswer: "9", difficulty: "easy" },

  // Medium (17)
  { id: 'math_m1', question: "Was ist 13 * 4?", options: ["42", "52", "62"], correctAnswer: "52", difficulty: "medium" },
  { id: 'math_m2', question: "Was ist 144 / 12?", options: ["11", "12", "14"], correctAnswer: "12", difficulty: "medium" },
  { id: 'math_m3', question: "Was ist 5% von 200?", options: ["5", "10", "20"], correctAnswer: "10", difficulty: "medium" },
  { id: 'math_m4', question: "Was ist 3/4 von 100?", options: ["25", "50", "75"], correctAnswer: "75", difficulty: "medium" },
  { id: 'math_m5', question: "Was ist 15 * 15?", options: ["215", "225", "255"], correctAnswer: "225", difficulty: "medium" },
  { id: 'math_m6', question: "Löse: x + 7 = 20. Was ist x?", options: ["13", "14", "27"], correctAnswer: "13", difficulty: "medium" },
  { id: 'math_m7', question: "Was ist der Umfang eines Quadrats mit der Seitenlänge 5?", options: ["10", "20", "25"], correctAnswer: "20", difficulty: "medium" },
  { id: 'math_m8', question: "Was ist 8/2(2+2)?", options: ["1", "8", "16"], correctAnswer: "16", difficulty: "medium" },
  { id: 'math_m9', question: "Was ist 30% von 150?", options: ["30", "45", "50"], correctAnswer: "45", difficulty: "medium" },
  { id: 'math_m10', question: "Was ist 7 * 8 + 4?", options: ["60", "84", "64"], correctAnswer: "60", difficulty: "medium" },
  { id: 'math_m11', question: "Was ist 2^4?", options: ["8", "16", "32"], correctAnswer: "16", difficulty: "medium" },
  { id: 'math_m12', question: "Löse: 2x = 18. Was ist x?", options: ["8", "9", "10"], correctAnswer: "9", difficulty: "medium" },
  { id: 'math_m13', question: "Was ist 1/2 + 1/4?", options: ["3/4", "2/6", "1/8"], correctAnswer: "3/4", difficulty: "medium" },
  { id: 'math_m14', question: "Was ist 120 / 5?", options: ["20", "24", "25"], correctAnswer: "24", difficulty: "medium" },
  { id: 'math_m15', question: "Was ist die Wurzel aus 81?", options: ["8", "9", "11"], correctAnswer: "9", difficulty: "medium" },
  { id: 'math_m16', question: "Was ist 18 * 3?", options: ["48", "54", "64"], correctAnswer: "54", difficulty: "medium" },
  { id: 'math_m17', question: "Was ist 100 - 33 - 22?", options: ["45", "44", "55"], correctAnswer: "45", difficulty: "medium" },
  { id: 'math_m18', question: "Was ist 14 * 5?", options: ["70", "60", "80"], correctAnswer: "70", difficulty: "medium" },
  { id: 'math_m19', question: "Was ist 125 / 5?", options: ["25", "15", "35"], correctAnswer: "25", difficulty: "medium" },
  { id: 'math_m20', question: "Was ist 20% von 50?", options: ["10", "5", "15"], correctAnswer: "10", difficulty: "medium" },
  { id: 'math_m21', question: "Löse: 2x - 4 = 10", options: ["7", "6", "8"], correctAnswer: "7", difficulty: "medium" },
  { id: 'math_m22', question: "Was ist 3^3?", options: ["27", "9", "81"], correctAnswer: "27", difficulty: "medium" },
  { id: 'math_m23', question: "Was ist 11 * 12?", options: ["132", "121", "144"], correctAnswer: "132", difficulty: "medium" },
  { id: 'math_m24', question: "Was ist 1/3 + 1/3?", options: ["2/3", "1/6", "2/6"], correctAnswer: "2/3", difficulty: "medium" },
  { id: 'math_m25', question: "Was ist die Wurzel aus 64?", options: ["8", "6", "4"], correctAnswer: "8", difficulty: "medium" },
  { id: 'math_m26', question: "Was ist 15% von 200?", options: ["30", "15", "45"], correctAnswer: "30", difficulty: "medium" },
  { id: 'math_m27', question: "Löse: x/2 = 8", options: ["16", "4", "10"], correctAnswer: "16", difficulty: "medium" },
  { id: 'math_m28', question: "Was ist 45 * 2 + 10?", options: ["100", "90", "110"], correctAnswer: "100", difficulty: "medium" },
  { id: 'math_m29', question: "Was ist 1/2 von 1/2?", options: ["1/4", "1/8", "1"], correctAnswer: "1/4", difficulty: "medium" },
  { id: 'math_m30', question: "Was ist der Flächeninhalt eines Rechtecks mit 4 und 5?", options: ["20", "9", "18"], correctAnswer: "20", difficulty: "medium" },
  { id: 'math_m31', question: "Was ist 1000 - 450?", options: ["550", "650", "450"], correctAnswer: "550", difficulty: "medium" },
  { id: 'math_m32', question: "Was ist 6 * 7?", options: ["42", "48", "36"], correctAnswer: "42", difficulty: "medium" },
  { id: 'math_m33', question: "Was ist 90 / 6?", options: ["15", "16", "14"], correctAnswer: "15", difficulty: "medium" },

  // Hard (16)
  { id: 'math_h1', question: "Was ist die Wurzel aus 225?", options: ["15", "25", "35"], correctAnswer: "15", difficulty: "hard" },
  { id: 'math_h2', question: "Löse: 3x - 5 = 16. Was ist x?", options: ["6", "7", "8"], correctAnswer: "7", difficulty: "hard" },
  { id: 'math_h3', question: "Was ist log10(1000)?", options: ["2", "3", "4"], correctAnswer: "3", difficulty: "hard" },
  { id: 'math_h4', question: "Was ist 7^3?", options: ["243", "343", "443"], correctAnswer: "343", difficulty: "hard" },
  { id: 'math_h5', question: "Was ist die Ableitung von x^2?", options: ["x", "2x", "x^3"], correctAnswer: "2x", difficulty: "hard" },
  { id: 'math_h6', question: "Was ist 0,2 * 0,3?", options: ["0,06", "0,6", "0,006"], correctAnswer: "0,06", difficulty: "hard" },
  { id: 'math_h7', question: "Was ist 2/3 / 4/5?", options: ["5/6", "8/15", "10/12"], correctAnswer: "5/6", difficulty: "hard" },
  { id: 'math_h8', question: "Löse: x^2 = 144. Was ist x?", options: ["12", "-12", "+12 und -12"], correctAnswer: "+12 und -12", difficulty: "hard" },
  { id: 'math_h9', question: "Was ist 17% von 300?", options: ["51", "34", "68"], correctAnswer: "51", difficulty: "hard" },
  { id: 'math_h10', question: "Was ist sin(90°) (im Gradmaß)?", options: ["0", "1", "-1"], correctAnswer: "1", difficulty: "hard" },
  { id: 'math_h11', question: "Was ist 24 * 15?", options: ["320", "340", "360"], correctAnswer: "360", difficulty: "hard" },
  { id: 'math_h12', question: "Was ist die Wurzel aus 256?", options: ["14", "16", "18"], correctAnswer: "16", difficulty: "hard" },
  { id: 'math_h13', question: "Was ist (3+4)^2?", options: ["49", "25", "14"], correctAnswer: "49", difficulty: "hard" },
  { id: 'math_h14', question: "Ein Auto fährt 120km/h. Wie weit kommt es in 45 Min?", options: ["80 km", "90 km", "100 km"], correctAnswer: "90 km", difficulty: "hard" },
  { id: 'math_h15', question: "Löse für y: 2y + x = 10, wenn x = 4.", options: ["3", "4", "5"], correctAnswer: "3", difficulty: "hard" },
  { id: 'math_h16', question: "Was ist der Logarithmus zur Basis 2 von 32?", options: ["4", "5", "6"], correctAnswer: "5", difficulty: "hard" },
  { id: 'math_h17', question: "Löse: 5x + 10 = 3x + 20", options: ["5", "10", "2"], correctAnswer: "5", difficulty: "hard" },
  { id: 'math_h18', question: "Was ist log2(64)?", options: ["6", "5", "8"], correctAnswer: "6", difficulty: "hard" },
  { id: 'math_h19', question: "Was ist (a+b)(a-b)?", options: ["a^2 - b^2", "a^2 + b^2", "a^2 - 2ab + b^2"], correctAnswer: "a^2 - b^2", difficulty: "hard" },
  { id: 'math_h20', question: "Was ist das Integral von 2x?", options: ["x^2", "2", "x^2 + C"], correctAnswer: "x^2 + C", difficulty: "hard" },
  { id: 'math_h21', question: "Was ist sin(30°)?", options: ["0,5", "1", "0"], correctAnswer: "0,5", difficulty: "hard" },
  { id: 'math_h22', question: "Was ist 2^10?", options: ["1024", "1000", "512"], correctAnswer: "1024", difficulty: "hard" },
  { id: 'math_h23', question: "Was ist die Wurzel aus 169?", options: ["13", "14", "15"], correctAnswer: "13", difficulty: "hard" },
  { id: 'math_h24', question: "Löse: x^2 - 4x + 4 = 0", options: ["2", "-2", "4"], correctAnswer: "2", difficulty: "hard" },
  { id: 'math_h25', question: "Was ist 12! / 10!?", options: ["132", "12", "144"], correctAnswer: "132", difficulty: "hard" },
  { id: 'math_h26', question: "Was ist die Ableitung von e^x?", options: ["e^x", "xe^(x-1)", "1 / e^x"], correctAnswer: "e^x", difficulty: "hard" },
  { id: 'math_h27', question: "Was ist 10% von 5% von 1000?", options: ["0,5", "5", "50"], correctAnswer: "0,5", difficulty: "hard" },
  { id: 'math_h28', question: "Welche Zahl ist eine Primzahl?", options: ["97", "91", "93"], correctAnswer: "97", difficulty: "hard" },
  { id: 'math_h29', question: "Was ist tan(45°)?", options: ["1", "0", "-1"], correctAnswer: "1", difficulty: "hard" },
  { id: 'math_h30', question: "Was ist 1 / (1/2)?", options: ["2", "0,5", "4"], correctAnswer: "2", difficulty: "hard" },
  { id: 'math_h31', question: "Was ist 25^2?", options: ["625", "525", "425"], correctAnswer: "625", difficulty: "hard" },
  { id: 'math_h32', question: "Löse: log(x) = 2 (Basis 10)", options: ["100", "20", "10"], correctAnswer: "100", difficulty: "hard" },
];

export const FRENCH_QUIZ_QUESTIONS: QuizQuestion[] = [
  // Easy (10)
  { id: 'fr_e1', question: "Was bedeutet 'chat' auf Deutsch?", options: ["Katze", "Hund", "Maus"], correctAnswer: "Katze", difficulty: "easy" },
  { id: 'fr_e2', question: "Welches Wort bedeutet 'Danke'?", options: ["Merci", "S'il vous plaît", "Bonjour"], correctAnswer: "Merci", difficulty: "easy" },
  { id: 'fr_e3', question: "Was bedeutet 'bonjour' auf Deutsch?", options: ["Guten Tag", "Auf Wiedersehen", "Gute Nacht"], correctAnswer: "Guten Tag", difficulty: "easy" },
  { id: 'fr_e4', question: "Wie heißt 'Schule' auf Französisch?", options: ["école", "classe", "cours"], correctAnswer: "école", difficulty: "easy" },
  { id: 'fr_e5', question: "Was bedeutet 'rouge'?", options: ["Rot", "Blau", "Grün"], correctAnswer: "Rot", difficulty: "easy" },
  { id: 'fr_e6', question: "Welches Wort ist ein Wochentag?", options: ["Lundi", "Premier", "Temps"], correctAnswer: "Lundi", difficulty: "easy" },
  { id: 'fr_e7', question: "Wie sagt man 'auf Wiedersehen'?", options: ["Au revoir", "Salut", "Allô"], correctAnswer: "Au revoir", difficulty: "easy" },
  { id: 'fr_e8', question: "Was bedeutet 'chien'?", options: ["Hund", "Pferd", "Vogel"], correctAnswer: "Hund", difficulty: "easy" },
  { id: 'fr_e9', question: "Was bedeutet 'une pomme'?", options: ["ein Apfel", "eine Birne", "eine Banane"], correctAnswer: "ein Apfel", difficulty: "easy" },
  { id: 'fr_e10', question: "Welches Wort ist die Zahl Drei?", options: ["trois", "très", "toi"], correctAnswer: "trois", difficulty: "easy" },

  // Medium (10)
  { id: 'fr_m1', question: "Wie bildet man das Passé Composé von 'parler' mit 'je'?", options: ["j'ai parlé", "je suis parlé", "je parlais"], correctAnswer: "j'ai parlé", difficulty: "medium" },
  { id: 'fr_m2', question: "Was bedeutet das Hilfsverb 'être'?", options: ["sein", "haben", "gehen"], correctAnswer: "sein", difficulty: "medium" },
  { id: 'fr_m3', question: "Welcher bestimmte Artikel gehört zu 'soleil' (Sonne)?", options: ["le", "la", "l'"], correctAnswer: "le", difficulty: "medium" },
  { id: 'fr_m4', question: "Was bedeutet das Verb 'vouloir'?", options: ["wollen", "können", "müssen"], correctAnswer: "wollen", difficulty: "medium" },
  { id: 'fr_m5', question: "Wie heißt das französische Wort für 'Haus'?", options: ["maison", "château", "bâtiment"], correctAnswer: "maison", difficulty: "medium" },
  { id: 'fr_m6', question: "Welches Verb bedeutet 'machen oder tun'?", options: ["faire", "aller", "prendre"], correctAnswer: "faire", difficulty: "medium" },
  { id: 'fr_m7', question: "Was ist das Gegenteil von 'grand'?", options: ["petit", "gros", "long"], correctAnswer: "petit", difficulty: "medium" },
  { id: 'fr_m8', question: "Ergänze: Nous ___ (haben) faim.", options: ["avons", "sommes", "ont"], correctAnswer: "avons", difficulty: "medium" },
  { id: 'fr_m9', question: "Was bedeutet 'ordinateur'?", options: ["Computer", "Fernseher", "Drucker"], correctAnswer: "Computer", difficulty: "medium" },
  { id: 'fr_m10', question: "Was ist die korrekte Form: Ils ___ (schreiben).", options: ["écrivent", "écrit", "écris"], correctAnswer: "écrivent", difficulty: "medium" },

  // Hard (10)
  { id: 'fr_h1', question: "Was ist das Subjonctif von 'faire' für 'que tu...'?", options: ["que tu fasses", "que tu fais", "que tu faces"], correctAnswer: "que tu fasses", difficulty: "hard" },
  { id: 'fr_h2', question: "Was ist das Subjonctif von 'être' für 'que je...'?", options: ["que je sois", "que je suis", "que je soye"], correctAnswer: "que je sois", difficulty: "hard" },
  { id: 'fr_h3', question: "Was ist das Gerundium (gérondif) von 'manger'?", options: ["en mangeant", "mangeant", "en mangant"], correctAnswer: "en mangeant", difficulty: "hard" },
  { id: 'fr_h4', question: "Welche Zeitenfolge gilt im Bedingungssatz Typ II?", options: ["Si + Imparfait -> Conditionnel Présent", "Si + Présent -> Futur Simple", "Si + Plus-que-parfait -> Conditionnel Passé"], correctAnswer: "Si + Imparfait -> Conditionnel Présent", difficulty: "hard" },
  { id: 'fr_h5', question: "Was bedeutet das Konnektor-Wort 'd'ailleurs'?", options: ["übrigens / außerdem", "woanders", "folglich"], correctAnswer: "übrigens / außerdem", difficulty: "hard" },
  { id: 'fr_h6', question: "Was bedeutet das Wort 'néanmoins'?", options: ["dennoch / nichtsdestotrotz", "niemals", "glücklicherweise"], correctAnswer: "dennoch / nichtsdestotrotz", difficulty: "hard" },
  { id: 'fr_h7', question: "Welches Relativpronomen ersetzt ein direktes Objekt?", options: ["que", "qui", "dont"], correctAnswer: "que", difficulty: "hard" },
  { id: 'fr_h8', question: "Wie lautet die korrekte weibliche Form von 'frais'?", options: ["fraîche", "fraise", "fraichement"], correctAnswer: "fraîche", difficulty: "hard" },
  { id: 'fr_h9', question: "Ergänze das Partizip: Elles se sont ___ (waschen).", options: ["lavées", "lavé", "laver"], correctAnswer: "lavées", difficulty: "hard" },
  { id: 'fr_h10', question: "Was bedeutet die Redewendung 'avoir le cafard'?", options: ["deprimiert sein", "hungrig sein", "wütend sein"], correctAnswer: "deprimiert sein", difficulty: "hard" }
];

export const GERMAN_QUIZ_QUESTIONS: QuizQuestion[] = [
  // Easy (10)
  { id: 'de_e1', question: "Welche Wortart beschreibt eine Eigenschaft (z. B. 'schön')?", options: ["Adjektiv", "Nomen", "Verb"], correctAnswer: "Adjektiv", difficulty: "easy" },
  { id: 'de_e2', question: "Wie schreibt man dieses Wort richtig?", options: ["Schifffahrt", "Schiffahrt", "Schifahrt"], correctAnswer: "Schifffahrt", difficulty: "easy" },
  { id: 'de_e3', question: "Was ist das Subjekt im Satz: 'Der Hund fängt den Ball.'?", options: ["Der Hund", "den Ball", "fängt"], correctAnswer: "Der Hund", difficulty: "easy" },
  { id: 'de_e4', question: "Welcher Buchstabe folgt im deutschen Alphabet nach 'O'?", options: ["P", "Q", "N"], correctAnswer: "P", difficulty: "easy" },
  { id: 'de_e5', question: "Welcher Satz ist im Präsens geschrieben?", options: ["Ich gehe nach Hause.", "Ich ging nach Hause.", "Ich bin nach Hause gegangen."], correctAnswer: "Ich gehe nach Hause.", difficulty: "easy" },
  { id: 'de_e6', question: "Was ist ein Synonym für 'fleißig'?", options: ["arbeitsam", "träge", "begabt"], correctAnswer: "arbeitsam", difficulty: "easy" },
  { id: 'de_e7', question: "Welcher Buchstabe wird nach einem kurzen Vokal oft verdoppelt?", options: ["Konsonant", "Vokal", "Umlaut"], correctAnswer: "Konsonant", difficulty: "easy" },
  { id: 'de_e8', question: "Wie nennt man die zeitliche Reihenfolge in einer Geschichte?", options: ["Chronologie", "Metrik", "Orthographie"], correctAnswer: "Chronologie", difficulty: "easy" },
  { id: 'de_e9', question: "Wie heißt der Begleiter eines Nomens (z. B. 'der, die, das')?", options: ["Artikel", "Pronomen", "Präposition"], correctAnswer: "Artikel", difficulty: "easy" },
  { id: 'de_e10', question: "Welches der folgenden Wörter ist ein Nomen?", options: ["Sonne", "gelb", "laufen"], correctAnswer: "Sonne", difficulty: "easy" },

  // Medium (10)
  { id: 'de_m1', question: "Welches Stilmittel liegt vor bei: 'Die Sonne lacht.'?", options: ["Personifikation", "Metapher", "Alliteration"], correctAnswer: "Personifikation", difficulty: "medium" },
  { id: 'de_m2', question: "In welcher Zeitform steht: 'Er hatte ein Buch gelesen.'?", options: ["Plusquamperfekt", "Perfekt", "Präteritum"], correctAnswer: "Plusquamperfekt", difficulty: "medium" },
  { id: 'de_m3', question: "Wer schrieb die berühmte Tragödie 'Faust'?", options: ["Johann Wolfgang von Goethe", "Friedrich Schiller", "Gotthold Ephraim Lessing"], correctAnswer: "Johann Wolfgang von Goethe", difficulty: "medium" },
  { id: 'de_m4', question: "Was bedeutet das Fremdwort 'redundant'?", options: ["überflüssig / mehrfach vorhanden", "wichtig", "fehlerhaft"], correctAnswer: "überflüssig / mehrfach vorhanden", difficulty: "medium" },
  { id: 'de_m5', question: "Welcher Fall (Kasus) antwortet auf die Frage 'Wessen?'?", options: ["Genitiv", "Dativ", "Akkusativ"], correctAnswer: "Genitiv", difficulty: "medium" },
  { id: 'de_m6', question: "Wie nennt man ein Wort, das vorwärts und rückwärts gelesen denselben Sinn ergibt (z. B. 'Anna')?", options: ["Palindrom", "Anagramm", "Homonym"], correctAnswer: "Palindrom", difficulty: "medium" },
  { id: 'de_m7', question: "Was beschreibt ein 'Oxymoron'?", options: ["Einen inneren Widerspruch", "Eine Übertreibung", "Einen milderen Ausdruck"], correctAnswer: "Einen inneren Widerspruch", difficulty: "medium" },
  { id: 'de_m8', question: "Welches Wort ist richtig getrennt?", options: ["In-ter-es-se", "In-te-res-se", "Int-er-es-se"], correctAnswer: "In-ter-es-se", difficulty: "medium" },
  { id: 'de_m9', question: "Was bedeutet die Redewendung 'Auf dem Holzweg sein'?", options: ["Sich irren", "Handwerklich begabt sein", "Einen Waldspaziergang machen"], correctAnswer: "Sich irren", difficulty: "medium" },
  { id: 'de_m10', question: "Was ist ein 'Neologismus'?", options: ["Eine Wortneuschöpfung", "Ein veraltetes Wort", "Ein Rechtschreibfehler"], correctAnswer: "Eine Wortneuschöpfung", difficulty: "medium" },

  // Hard (10)
  { id: 'de_h1', question: "Wie nennt man das Reimschema 'abab'?", options: ["Kreuzreim", "Paarreim", "Umarmender Reim"], correctAnswer: "Kreuzreim", difficulty: "hard" },
  { id: 'de_h2', question: "Welches Versmaß hat einen unbetont-betonten Rhythmus (xX)?", options: ["Jambus", "Trochäus", "Anapäst"], correctAnswer: "Jambus", difficulty: "hard" },
  { id: 'de_h3', question: "Welches Stilmittel liegt bei der Phrase 'Keine Kleinigkeit' vor?", options: ["Litotes", "Synekdoche", "Chiasmus"], correctAnswer: "Litotes", difficulty: "hard" },
  { id: 'de_h4', question: "Was bezeichnet eine 'Antithese'?", options: ["Eine Gegenüberstellung von Begriffen", "Einen Satz ohne Verb", "Eine syntaktische Umkehrung"], correctAnswer: "Eine Gegenüberstellung von Begriffen", difficulty: "hard" },
  { id: 'de_h5', question: "Welchem literarischen Werk der Aufklärung entstammt die Ringparabel?", options: ["Nathan der Weise", "Kabale und Liebe", "Die Leiden des jungen Werther"], correctAnswer: "Nathan der Weise", difficulty: "hard" },
  { id: 'de_h6', question: "Was ist der Konjunktiv I von 'er läuft'?", options: ["er laufe", "er liefe", "er würde laufen"], correctAnswer: "er laufe", difficulty: "hard" },
  { id: 'de_h7', question: "Welcher Begriff bezeichnet das Schema des klassischen Dramas (nach Freytag)?", options: ["Fünf-Akt-Schema", "Drei-Säulen-Prinzip", "Dodekaeder"], correctAnswer: "Fünf-Akt-Schema", difficulty: "hard" },
  { id: 'de_h8', question: "Was ist ein 'Chiasmus'?", options: ["Kreuzstellung von Satzgliedern", "Gleichlauf von Satzgliedern", "Auslassung eines Wortes"], correctAnswer: "Kreuzstellung von Satzgliedern", difficulty: "hard" },
  { id: 'de_h9', question: "Welche Literaturepoche wird auf ca. 1770 bis 1785 datiert?", options: ["Sturm und Drang", "Romantik", "Biedermeier"], correctAnswer: "Sturm und Drang", difficulty: "hard" },
  { id: 'de_h10', question: "Was bedeutet das mittelhochdeutsche Wort 'minne'?", options: ["Liebe / Verehrung", "Erinnerung", "Gesang"], correctAnswer: "Liebe / Verehrung", difficulty: "hard" }
];

